import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gestionale Ristorativo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}

        {/* Contenitore degli avvisi: senza questo, toast.error() non ha dove
            comparire e non succede niente. In alto a destra come deciso in
            STRUTTURA.md, per non litigare con la barra di navigazione in basso. */}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
